Feature/fix search compare lings scenario
linguisticexplorer/Linguistic-Explorer pull request #159
Opened 2016-09-09 21:34 UTC by AndreaOlivieri

@hab278 @dej611 

All the following commits are made for fixing all problems in features/search_compare_lings.feature:
- I added somme `classes` and `ids` in compare_results.hamstache because in some steps of search_compare_lings.feature can't find them
- I added a unless condition for the `common` and `differents` variable, because when common was empty it raised an error
- I delete one step on the last scenario of search_compare_lings.feature because after you click in "compare" radio button of languages scope, you can't click the other "compare" radio button of speakers scope. I think is blocked by javascript

2016-09-28 07:31 UTC, dej611 requested changes

2016-09-28 07:31 UTC, dej611 commented on app/presenters/search_json.rb
> +    unless commons.empty?
I'd prefer a positive condition, rather than negative:

```ruby
if something.present?
```

rather than using `unless`

2016-09-28 07:31 UTC, dej611 commented on app/presenters/search_json.rb
> +    unless differents.empty?
Ditto.

2016-10-08 22:42 UTC, AndreaOlivieri commented
This PR is made by @hab278. 
I can't push any changes to hab278:feature/fix-search_compare_lings-scenario
@dej611

2016-10-10 18:33 UTC, dej611 commented
Close this one as a new one from @AndreaOlivieri will come soon with same fixes.

2016-10-10 18:33 UTC, closed without merging