fixed problem #103, Seed data in project
linguisticexplorer/Linguistic-Explorer pull request #170
Opened 2016-10-05 15:27 UTC by AndreaOlivieri

Added seed data into project

2016-10-05 20:23 UTC, dej611 commented
Need to add the roles data in here.

2016-10-10 18:23 UTC, dej611 requested changes

2016-10-10 18:23 UTC, dej611 commented on lib/group_data/importer.rb
> +      print_to_console "processing #{csv_size(:role)} memberships"
Can you change the rest of the statement too here?

```ruby
print_to_console "processing #{csv_size(:role)} roles"
```

2016-10-10 19:50 UTC, AndreaOlivieri commented on lib/group_data/importer.rb
> +      print_to_console "processing #{csv_size(:role)} memberships"
It's done

2016-10-19 19:31 UTC, dej611 approved these changes

2016-10-19 19:31 UTC, merged