Don't merge it is a test
linguisticexplorer/Linguistic-Explorer pull request #184
Opened 2016-11-14 15:50 UTC by AndreaOlivieri

2016-11-15 08:37 UTC, dej611 requested changes

2016-11-15 08:37 UTC, dej611 commented on Gemfile
>    gem 'pry'
Can you restore this `development` group?

2016-11-15 15:33 UTC, AndreaOlivieri commented on Gemfile
>    gem 'pry'
if I restore this group, it will not work

2016-11-16 19:41 UTC, dej611 commented on Gemfile
>    gem 'pry'
debugging sounds like a thing that belongs to `development`.
Debugging should not be in `testing`.

2016-11-16 22:57 UTC, merged